"""Add User.email

Revision ID: 7cd9faeaa7dc
Revises: 85dfb665c0ca
Create Date: 2024-12-09 13:40:35.800435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7cd9faeaa7dc'
down_revision: Union[str, None] = '85dfb665c0ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_user', sa.Column('email', sa.String(length=256), nullable=True))
    op.alter_column('service_user', 'username',
               existing_type=mysql.VARCHAR(length=16),
               nullable=False)
    op.alter_column('service_user', 'password',
               existing_type=mysql.VARCHAR(length=60),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('service_user', 'password',
               existing_type=mysql.VARCHAR(length=60),
               nullable=True)
    op.alter_column('service_user', 'username',
               existing_type=mysql.VARCHAR(length=16),
               nullable=True)
    op.drop_column('service_user', 'email')
    # ### end Alembic commands ###
