"""Add ChatRoom

Revision ID: ad4db8426de3
Revises: d441c321e93d
Create Date: 2024-12-12 14:43:44.737389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad4db8426de3'
down_revision: Union[str, None] = 'd441c321e93d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('chat_message', sa.Column('chat_room_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chat_message', 'chat_room', ['chat_room_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_message', type_='foreignkey')
    op.drop_column('chat_message', 'chat_room_id')
    op.drop_table('chat_room')
    # ### end Alembic commands ###
