"""Add User.social_provider

Revision ID: deaf69a9f03d
Revises: 7cd9faeaa7dc
Create Date: 2024-12-10 11:54:56.329944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'deaf69a9f03d'
down_revision: Union[str, None] = '7cd9faeaa7dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_user', sa.Column('social_provider', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_user', 'social_provider')
    # ### end Alembic commands ###
