services:
  db:
    container_name: ozcoding-db
    image: mysql:8.0
    restart: always
    volumes:
      - local_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ozcoding_pw
      MYSQL_DATABASE: ozcoding
    ports:
      - "33060:3306"

volumes:
  local_db:
